"""create tracking table

Revision ID: f22c58959839
Revises: 09c8373e593e
Create Date: 2026-07-03 11:12:25.846912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22c58959839'
down_revision: Union[str, Sequence[str], None] = '09c8373e593e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_delivery_id'), 'tracking', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_tracking_id'), 'tracking', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_id'), table_name='tracking')
    op.drop_index(op.f('ix_tracking_delivery_id'), table_name='tracking')
    op.drop_table('tracking')
    # ### end Alembic commands ###
